### PR TITLE
removes app.legacyFilesToAppend deprecation issue

### PR DESCRIPTION
**Pull request by Hirtenknogger**

### CODE REVIEW

**Comment by remkoboschker** [comment]
Should we fix build errors?

**Comment by Hirtenknogger** [comment]
That would be great. You want to try it?

**Comment by remkoboschker** [comment]
sure, I'll give it a go.

**Comment by mike-north** [comment]
Thanks so much for helping out with this! I lumped the fix in with #101 which was just merged

**Pull request closed without merging**
